/*
 ============================================================================
 Name        : MPC_SHA256_VERIFIER.c
 Author      : Sobuno
 Version     : 0.1
 Description : Verifies a proof for SHA-256 generated by MPC_SHA256.c
 ============================================================================
 */

#include "MPC_SHA256_VERIFIER.h"
#include "shared.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

void printbits(uint32_t n) {
  if (n) {
    printbits(n >> 1);
    printf("%d", n & 1);
  }
}

int main(void) {
  setbuf(stdout, NULL);
  init_EVP();
  openmp_thread_setup();

  printf("Iterations of SHA: %d\n", NUM_ROUNDS);

  clock_t begin = clock(), delta, deltaFiles;

  a2 a2s[NUM_ROUNDS];
  z2 z2s[NUM_ROUNDS];
  FILE *file;

  char outputFile[3 * sizeof(int) + 8];
  sprintf(outputFile, "out%i_eq.bin", NUM_ROUNDS);
  file = fopen(outputFile, "rb");
  if (!file) {
    printf("Unable to open file!");
  }
  fread(&a2s, sizeof(a2), NUM_ROUNDS, file);
  fread(&z2s, sizeof(z2), NUM_ROUNDS, file);
  fclose(file);

  // TODO: define reconstruct for a2 and z2
  a as[2][NUM_ROUNDS];
  z zs[2][NUM_ROUNDS];
  uint32_t y[2][8];

  for (int c = 0; c < 2; c++) {
    for (int k = 0; k < NUM_ROUNDS; k++) {
      memcpy(as[c][k].h, a2s[k].h, sizeof(as[c][k].h));
      memcpy(as[c][k].yp, a2s[k].yp[c], sizeof(as[c][k].yp));

      memcpy(zs[c][k].ke, z2s[k].ke, sizeof(zs[c][k].ke));
      memcpy(zs[c][k].ke1, z2s[k].ke1, sizeof(zs[c][k].ke1));

      memcpy(zs[c][k].re, z2s[k].re, sizeof(zs[c][k].re));
      memcpy(zs[c][k].re1, z2s[k].re1, sizeof(zs[c][k].re1));

      memcpy(zs[c][k].ve.x, z2s[k].ve.x, sizeof(zs[c][k].ve.x));
      memcpy(zs[c][k].ve1.x, z2s[k].ve1.x, sizeof(zs[c][k].ve1.x));

      memcpy(zs[c][k].ve.y, z2s[k].ve.y[c], sizeof(zs[c][k].ve.y));
      memcpy(zs[c][k].ve1.y, z2s[k].ve1.y[c], sizeof(zs[c][k].ve1.y));
    }
    reconstruct(as[c][0].yp[0], as[c][0].yp[1], as[c][0].yp[2], y[c]);
  }

  printf("Proof for hashes:\n\t");
  for (int i = 0; i < 8; i++) {
    printf("%02X", y[0][i]);
  }
  printf("\n\t");
  for (int i = 0; i < 8; i++) {
    printf("%02X", y[1][i]);
  }
  printf("\n");

  for (int i = 0; i < 8; i++) {
    y[0][i] ^= y[1][i];
  }

  deltaFiles = clock() - begin;
  int inMilliFiles = deltaFiles * 1000 / CLOCKS_PER_SEC;
  printf("Loading files: %ju\n", (uintmax_t)inMilliFiles);

  clock_t beginE = clock(), deltaE;
  int es[NUM_ROUNDS];

  H3_2(y[0], a2s, NUM_ROUNDS, es);

  deltaE = clock() - beginE;
  int inMilliE = deltaE * 1000 / CLOCKS_PER_SEC;
  printf("Generating E: %ju\n", (uintmax_t)inMilliE);

  clock_t beginV = clock(), deltaV;
  for (int c = 0; c < 2; c++) {
#pragma omp parallel for
    for (int i = 0; i < NUM_ROUNDS; i++) {
      int verifyResult = verify_hash2(a2s[i], es[i], z2s[i]);
      if (verifyResult != 0) {
        printf("Not Verifiedd %d\n", i);
      } else {
        verifyResult = verify(as[c][i], es[i], zs[c][i]);
        if (verifyResult != 0) {
          printf("Not Verified %d\n", i);
        }
      }
    }
  }
  deltaV = clock() - beginV;

  int inMilliV = deltaV * 1000 / CLOCKS_PER_SEC;
  printf("Verifying: %ju\n", (uintmax_t)inMilliV);

  delta = clock() - begin;
  int inMilli = delta * 1000 / CLOCKS_PER_SEC;

  printf("Total time: %ju\n", (uintmax_t)inMilli);

  openmp_thread_cleanup();
  cleanup_EVP();
  return EXIT_SUCCESS;
}
