/*
 ============================================================================
 Name        : MPC_SHA256_VERIFIER.c
 Author      : Sobuno
 Version     : 0.1
 Description : Verifies a proof for SHA-256 generated by MPC_SHA256.c
 ============================================================================
 */
#include "MPC_SHA256_VERIFIER.h"
#include "MPC_inner_prod.h"
#include "shared.h"
#include <stdatomic.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

void printbits(uint32_t n) {
  if (n) {
    printbits(n >> 1);
    printf("%d", n & 1);
  }
}

bool mpc_halevi_micali_verifier(UniversalHash H, a as[NUM_ROUNDS],
                                z zs[NUM_ROUNDS], int es[NUM_ROUNDS]) {
  atomic_bool verified = true;
#pragma omp parallel for
  for (int i = 0; i < NUM_ROUNDS; i++) {
    if (!verify_hash(as[i], es[i], zs[i])) {
      printf("(%d) Commitment not verified!\n", i);
      verified = false;
    }
    if (verify(as[i], es[i], zs[i]) != 0) {
      printf("(%d) SHA256 not verified!\n", i);
      verified = false;
    }

    uint32_t m[2] = {zs[i].ve.msg, zs[i].ve1.msg};
    uint32_t r[L_WORDS][2];
    for (int j = 0; j < L_WORDS; j++) {
      memcpy(&r[j][0], &zs[i].ve.x[j * 4], sizeof(uint32_t));
      memcpy(&r[j][1], &zs[i].ve1.x[j * 4], sizeof(uint32_t));
    }

    if (!mpc_inner_prod_verify(H, m, r, as[i].y2p, es[i])) {
      printf("(%d) Inner product not verified!\n", i);
      verified = false;
    }
  }
  return verified;
}

int main(void) {
  setbuf(stdout, NULL);
  openmp_thread_setup();

  printf("Iterations of SHA: %d\n", NUM_ROUNDS);

  clock_t begin = clock(), delta, deltaFiles;

  UniversalHash h;
  uint8_t keyA[16];
  a as[NUM_ROUNDS];
  z zs[NUM_ROUNDS];
  FILE *file;

  char outputFile[3 * sizeof(int) + 8];
  sprintf(outputFile, "out%i.bin", NUM_ROUNDS);
  file = fopen(outputFile, "rb");
  if (!file) {
    printf("Unable to open file!");
    exit(EXIT_FAILURE);
  }
  int nRead = 0;
  nRead += fread(keyA, sizeof(keyA), 1, file);
  nRead += fread(&h.b, sizeof(h.b), 1, file);
  nRead += fread(&as, sizeof(a), NUM_ROUNDS, file);
  nRead += fread(&zs, sizeof(z), NUM_ROUNDS, file);

  fclose(file);
  if (nRead != 2 * NUM_ROUNDS + 2) {
    printf("Unable to parse proof!\n");
    exit(EXIT_FAILURE);
  }

  expand_A(h.A, keyA);
  uint32_t y[8];
  reconstruct(as[0].yp[0], as[0].yp[1], as[0].yp[2], y);
  printf("Proof for hash: ");
  for (int i = 0; i < 8; i++) {
    printf("%02X", y[i]);
  }
  printf("\n");

  deltaFiles = clock() - begin;
  int inMilliFiles = deltaFiles * 1000 / CLOCKS_PER_SEC;
  printf("Loading files: %ju\n", (uintmax_t)inMilliFiles);

  clock_t beginE = clock(), deltaE;
  int es[NUM_ROUNDS];
  H3(y, as, NUM_ROUNDS, h, es);
  deltaE = clock() - beginE;
  int inMilliE = deltaE * 1000 / CLOCKS_PER_SEC;
  printf("Generating E: %ju\n", (uintmax_t)inMilliE);

  clock_t beginV = clock(), deltaV;
  mpc_halevi_micali_verifier(h, as, zs, es);
  deltaV = clock() - beginV;
  int inMilliV = deltaV * 1000 / CLOCKS_PER_SEC;
  printf("Verifying: %ju\n", (uintmax_t)inMilliV);

  delta = clock() - begin;
  int inMilli = delta * 1000 / CLOCKS_PER_SEC;

  printf("Total time: %ju\n", (uintmax_t)inMilli);

  openmp_thread_cleanup();
  return EXIT_SUCCESS;
}
