/*
 ============================================================================
 Name        : MPC_SHA256_VERIFIER.c
 Author      : Sobuno
 Version     : 0.1
 Description : Verifies a proof for SHA-256 generated by MPC_SHA256.c
 ============================================================================
 */
#include "MPC_SHA256_VERIFIER.h"
#include "MPC_inner_prod.h"
#include "shared.h"
#include <bits/pthreadtypes.h>
#include <omp.h>
#include <pthread.h>
#include <stdatomic.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

void printbits(uint32_t n) {
  if (n) {
    printbits(n >> 1);
    printf("%d", n & 1);
  }
}

static inline void update_clock(double beginClock, double *clockToUpdate) {
  double deltaT = (omp_get_wtime() - beginClock) * 1000;
  *clockToUpdate += deltaT;
}

int read_hash(FILE *f, uint8_t keyH[16], UniversalHash *H) {
  unsigned char buf[16 + sizeof(H->b)];

  unsigned long nRead = fread(buf, 1, sizeof(buf), f);
  if (nRead == sizeof(buf)) {
    memcpy(keyH, buf, 16);
    memcpy(H->b, buf + 16, sizeof(H->b));
  }
  return (nRead == sizeof(buf) ? 0 : -1);
}

int read_zk_proof_at(FILE *f, unsigned char *buf, size_t bufSize, int k,
                     a *a_ptr, z *z_ptr) {
  off_t initial_offset = 16 + MSG_BYTES;

  size_t proofSize = sizeof(a) + sizeof(z_disk);
  if (bufSize < proofSize) {
    return -1;
  }

  // read buffer
  int fd = fileno(f);
  off_t off = initial_offset + (off_t)k * proofSize;
  ssize_t nRead = pread(fd, buf, proofSize, off);
  if (nRead != proofSize) {
    return -1;
  }

  size_t bufIdx = 0;
  memcpy(a_ptr, buf, sizeof(*a_ptr));
  bufIdx += sizeof(*a_ptr);

  memcpy(z_ptr->ke, buf + bufIdx, sizeof(z_ptr->ke));
  bufIdx += sizeof(z_ptr->ke);
  memcpy(z_ptr->ke1, buf + bufIdx, sizeof(z_ptr->ke1));
  bufIdx += sizeof(z_ptr->ke1);

  memcpy(z_ptr->re, buf + bufIdx, sizeof(z_ptr->re));
  bufIdx += sizeof(z_ptr->re);
  memcpy(z_ptr->re1, buf + bufIdx, sizeof(z_ptr->re1));
  bufIdx += sizeof(z_ptr->re1);

  // allocate views memory
  z_ptr->ve = malloc(sizeof(View));
  z_ptr->ve1 = malloc(sizeof(View));
  if (!z_ptr->ve || !z_ptr->ve1) {
    return -1;
  }

  memcpy(z_ptr->ve, buf + bufIdx, sizeof(View));
  bufIdx += sizeof(*z_ptr->ve);
  memcpy(z_ptr->ve1, buf + bufIdx, sizeof(View));
  bufIdx += sizeof(*z_ptr->ve1);

  return 0;
}

bool mpc_halevi_micali_verifier(UniversalHash *H, a *a, z *z, int e) {

  if (!verify_hash(a, e, z)) {
    return false;
  }
  if (verify(a, e, z) != 0) {
    return false;
  }

  uint32_t m[MSG_WORDS][2];
  for (int i = 0; i < MSG_WORDS; i++) {
    load_u32_le(&m[i][0], &z->ve->msg[i * 4]);
    load_u32_le(&m[i][1], &z->ve1->msg[i * 4]);
  };
  uint32_t r[L_WORDS][2];
  for (int j = 0; j < L_WORDS; j++) {
    memcpy(&r[j][0], &z->ve->x[j * 4], sizeof(uint32_t));
    memcpy(&r[j][1], &z->ve1->x[j * 4], sizeof(uint32_t));
  }

  if (!mpc_universal_hash_verifier(H, m, r, a->y2p, e)) {
    return false;
  }
  return true;
}

void print_message(uint32_t y[8]) {
  printf("Proof for hash: ");
  for (int i = 0; i < 8; i++) {
    printf("%02X", y[i]);
  }
  printf("\n");
}

int main(void) {
  setbuf(stdout, NULL);
  openmp_thread_setup();
  printf("Iterations of SHA: %d\n", NUM_ROUNDS);

  static double inMilli = 0;

  double begin = omp_get_wtime();

  UniversalHash h;
  uint8_t keyA[16];
  FILE *file;

  char outputFile[3 * sizeof(int) + 8];
  sprintf(outputFile, "out%i.bin", NUM_ROUNDS);
  file = fopen(outputFile, "rb");
  if (!file) {
    printf("Unable to open file!");
    exit(EXIT_FAILURE);
  }

  if (read_hash(file, keyA, &h) != 0) {
    fprintf(stderr, "Unable to parse proof!\n");
    exit(EXIT_FAILURE);
  }
  expand_A(h.A, keyA);

  EVP_MD_CTX *base_ctx = setupSHA256();
  EVP_DigestUpdate(base_ctx, h.A, sizeof(h.A));
  EVP_DigestUpdate(base_ctx, h.b, sizeof(h.b));

  atomic_int io_error = 0;
#pragma omp parallel
  {
    // Init thread state
    a a;
    z z;
    uint32_t y[8];
    EVP_MD_CTX *ctx = EVP_MD_CTX_new();

    // Pack into one contiguous buffer to write once
    ssize_t bufSize = sizeof(a) + sizeof(z) + 2 * sizeof(View);
    unsigned char *bufWrite = malloc(bufSize);

#pragma omp for
    for (int k = 0; k < NUM_ROUNDS; k++) {
      if (atomic_load(&io_error)) {
        continue;
      }

      if (read_zk_proof_at(file, bufWrite, bufSize, k, &a, &z) != 0) {
        atomic_store(&io_error, true);
      }

      reconstruct(a.yp[0], a.yp[1], a.yp[2], y);

      int e;
      EVP_MD_CTX_copy_ex(ctx, base_ctx);
      H3(ctx, y, &a, 1, &e);
      if (!mpc_halevi_micali_verifier(&h, &a, &z, e)) {
        printf("(%d) failed\n", k);
        exit(EXIT_FAILURE);
      }
    }

    // clear state
    free(bufWrite);
    if (z.ve) {
      free(z.ve);
    }
    if (z.ve1) {
      free(z.ve1);
    }
#pragma omp single nowait
    print_message(y);
  }
  update_clock(begin, &inMilli);

  printf("Total time: %ju\n", (uintmax_t)inMilli);

  fclose(file);
  openmp_thread_cleanup();
  return EXIT_SUCCESS;
}
